export const GLOSSARY: Record<string, string> = {
  "loss of function": "A change in a gene that makes its protein work less, or not at all.",
  "loss-of-function": "A change in a gene that makes its protein work less, or not at all.",
  "gain of function": "A change that makes the protein overactive, or active when it should not be.",
  "gain-of-function": "A change that makes the protein overactive, or active when it should not be.",
  "haploinsufficiency": "One working copy of the gene is not enough, so there is too little of the protein.",
  "dominant negative": "A faulty protein that gets in the way of the healthy copy.",
  "variant effect": "What a gene change does to the protein: less function, more function, or interference.",
  "phenotype": "An observable feature of a disease, such as a symptom or a test result.",
  "phenotypes": "Observable features of a disease, such as symptoms or test results.",
  "natural history study": "A study that follows people over time, without giving a treatment, to learn how a condition usually unfolds.",
  "natural history": "How a condition usually unfolds over time without treatment.",
  "registry": "A list of patients who agreed to be counted or contacted for research, often with health information.",
  "encephalopathy": "A condition in which brain function is affected.",
  "epileptic encephalopathy": "Seizures and abnormal brain activity that themselves hold back development.",
  "mechanism": "How a gene change leads to disease.",
  "hypothesis": "An idea worth testing. It has not been shown to be true.",
  "computed": "Worked out by a program from other data, not directly observed.",
  "in vitro": "In cells or a dish, not in a person or an animal.",
  "sodium channel": "A pore in nerve cells that lets sodium in and out and controls electrical signals.",
  "potassium channel": "A pore in nerve cells that lets potassium out and helps switch electrical signals off.",
  "synaptic vesicle release": "How nerve cells release chemical messengers to talk to each other.",
  "confidence": "How much we trust a link, from 0 to 1. A rule of thumb, not a probability.",
  "cluster": "A group of diseases that look alike on symptoms and in the literature.",
  "benign": "Mild. Here: a milder condition caused by the same gene.",
  "expert review": "A specialist should check this before anyone relies on it.",
  "trial readiness": "Preparing outcome measures and patient data so a future trial can start quickly.",
  "HPO": "Human Phenotype Ontology: a standard dictionary of symptoms.",
  "OMIM": "A catalogue of genetic diseases, used here as the disease ID.",
  "ORCID": "A unique ID that researchers use to tell themselves apart from namesakes.",
  "entailment": "Whether a quoted sentence, by itself, really says what we claim it says.",
  "quoted span": "The exact words from the paper that a claim is based on.",
  "variant": "A change in a gene's DNA.",
  "gene": "A stretch of DNA that carries the instructions for one protein.",
  "seizure": "A burst of abnormal electrical activity in the brain.",
  "developmental and epileptic encephalopathy": "A condition where frequent seizures and the gene change itself both slow a child's development.",
  "EEG": "A painless test that records the brain's electrical activity through small sensors on the scalp.",
  "status epilepticus": "A seizure that lasts too long, or seizures that follow each other without recovery in between. It is an emergency.",
  "burst suppression": "A severe EEG pattern: bursts of activity separated by near-silence.",
  "hypsarrhythmia": "A chaotic EEG pattern often seen with infantile spasms.",
  "MONDO": "A shared dictionary of diseases that links the different names used by other catalogues.",
  "PMID": "The ID number of a paper in PubMed, the US library of medical research.",
  "ClinicalTrials.gov": "The public US registry of clinical studies around the world.",
  "de novo": "A gene change that is new in the child and was not inherited from either parent.",
  "synapse": "The tiny gap where one brain cell passes a signal to the next.",
  "neuron": "A brain cell that sends electrical and chemical signals.",
  "ion channel": "A tiny gate in a cell's surface that lets charged particles in or out.",
  "kinase": "An enzyme that switches other proteins on or off by adding a small chemical tag.",
  "benign familial infantile seizures": "Seizures in the first year of life that run in families and usually stop on their own, with normal development.",
};
const keys = Object.keys(GLOSSARY).sort((a, b) => b.length - a.length);
export const GLOSS_RE = new RegExp(`\\b(${keys.map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})\\b`, "gi");
export const define = (t: string) => GLOSSARY[t.toLowerCase()];
